name: request_ad_permission_page_ui
description: "free flutter ui is all you need"
#publish_to: 'none'
#repository: https://github.com/melodysdreamj/uihub

version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  styled_widget: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - assets/uihub/request_ad_permission_page_ui/
  uses-material-design: true

topics:
  - uihub